# Generated by Django 2.0.7 on 2018-08-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
