# Generated by Django 2.0.7 on 2018-08-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180802_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name_plural': 'Order Histories'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name_plural': 'Shopping Carts'},
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
