# Generated by Django 2.0.7 on 2018-07-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180726_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='items',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
