# Generated by Django 2.0.7 on 2018-07-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180726_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='orders.Category'),
        ),
    ]
