# Generated by Django 2.0.7 on 2018-07-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pizza_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ManyToManyField(null=True, related_name='size', to='orders.Size'),
        ),
    ]
