# Generated by Django 2.0.7 on 2018-07-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180726_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name', 'category']},
        ),
    ]
