# Generated by Django 2.0.7 on 2018-07-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_topping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ['name']},
        ),
    ]
