# Generated by Django 2.0.7 on 2018-07-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(null=True, related_name='size', to='orders.Size'),
        ),
    ]
