# Generated by Django 2.0.7 on 2018-07-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20180728_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='size',
        ),
        migrations.AddField(
            model_name='price',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='orders.Size'),
        ),
    ]
