# Generated by Django 2.0.7 on 2018-07-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20180728_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
