# Generated by Django 2.0.7 on 2018-07-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20180728_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='orders.Category'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='item', to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
