# Generated by Django 2.0.7 on 2018-07-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20180728_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.ForeignKey(limit_choices_to={'name': 'Salads'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='orders.Category'),
        ),
    ]
