# Generated by Django 2.0.7 on 2018-07-28 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20180728_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='category',
        ),
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
        migrations.RemoveField(
            model_name='price',
            name='size',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
