# Generated by Django 2.0.7 on 2018-07-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_shoppingcart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topping',
            new_name='Extra',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Item'),
        ),
    ]
