# Generated by Django 2.0.7 on 2018-07-29 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20180729_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='category',
            field=models.ManyToManyField(to='orders.Category'),
        ),
        migrations.AddField(
            model_name='extra',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
