# Generated by Django 2.0.7 on 2018-07-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20180729_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='category',
        ),
        migrations.AddField(
            model_name='extra',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Category'),
        ),
    ]
