# Generated by Django 2.0.7 on 2018-07-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20180729_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='categories',
        ),
    ]
