# Generated by Django 2.0.7 on 2018-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_extra_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='items',
            field=models.ManyToManyField(blank=True, to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='categories',
            field=models.ManyToManyField(blank=True, to='orders.Category'),
        ),
    ]
