# Generated by Django 2.0.7 on 2018-07-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20180731_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddOn',
        ),
        migrations.AddField(
            model_name='item',
            name='customizeable',
            field=models.BooleanField(default=False),
        ),
    ]
