# Generated by Django 2.0.7 on 2018-07-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_auto_20180731_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='customizeable',
        ),
        migrations.AddField(
            model_name='category',
            name='customizeable',
            field=models.BooleanField(default=False),
        ),
    ]
