# Generated by Django 2.0.7 on 2018-07-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20180731_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Item'),
        ),
    ]
