# Generated by Django 2.0.7 on 2018-07-31 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_auto_20180731_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='items',
        ),
    ]
