# Generated by Django 2.0.7 on 2018-07-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_remove_extra_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Item'),
        ),
    ]
