# Generated by Django 2.0.7 on 2018-08-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_auto_20180731_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extras_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
