# Generated by Django 2.0.7 on 2018-08-01 05:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_auto_20180801_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='custom_items',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
