# Generated by Django 2.0.7 on 2018-08-01 05:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_shoppingcart_custom_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='custom_items',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
