# Generated by Django 2.0.7 on 2018-08-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_auto_20180801_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='custom_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
