# Generated by Django 2.0.7 on 2018-08-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_auto_20180801_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='custom_items',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
